defaults: &defaults
  adapter: postgresql
  encoding: unicode
  database: "<%= ENV['DB_NAME'] %>"
  host: "<%= ENV['DB_HOST'] %>"
  pool: 5
  username: "<%= ENV['DB_USERNAME'] %>"
  password: "<%= ENV['DB_PASSWORD'] %>"

development:
  <<: *defaults
  port: 5432

production:
  <<: *defaults