development:
  adapter: postgresql
  encoding: unicode
  database: "rolldice"
  host: localhost
  port: 5432
  pool: 5
  username: "victor"
  password: "88255632"

production:
  adapter: postgresql
  encoding: unicode
  database: "rolldice"
  host: ep-young-wave-31219132.us-east-2.aws.neon.tech
  pool: 5
  username: "VictorEmanuell"
  password: "frBOnv1J0XcU"